In [ ]:
import pandas as pd
import numpy as np
# Untuk pemodelan
import tensorflow as tf
from tensorflow import keras
# Untuk mengupload file
from google.colab import files

In [ ]:
# Upload semua dataset yang dipakai
uploaded = files.upload()

Saving tourism_rating.csv to tourism_rating.csv
Saving tourism_with_id.csv to tourism_with_id.csv
Saving user_new.csv to user_new.csv

In [ ]:
# Menyimpan masing-masing dataset kedalam variabel

rating = pd.read_csv('tourism_rating.csv')
place = pd.read_csv('tourism_with_id.csv')
user = pd.read_csv('user_new.csv')

In [ ]:
# Membuang kolom yang tidak dipakai

place = place.drop(['Unnamed: 11','Unnamed: 12'],axis=1)
place = place.drop('Time_Minutes', axis=1)
place.head(2)

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Coordinate,Lat,Long
0,1,Monumen Nasional,Monumen Nasional atau yang populer disingkat d...,Budaya,Jakarta,20000,4.6,"{'lat': -6.1753924, 'lng': 106.8271528}",-6.175392,106.827153
1,2,Kota Tua,"Kota tua di Jakarta, yang juga bernama Kota Tu...",Budaya,Jakarta,0,4.6,"{'lat': -6.137644799999999, 'lng': 106.8171245}",-6.137645,106.817125

In [ ]:
# Merubah data agar hanya dari Kota Bandung

place = place[place['City']=='Bandung']
place.head(2)

,Place_Id,Place_Name,Description,Category,City,Price,Rating,Coordinate,Lat,Long
210,211,GunungTangkuban perahu,Gunung Tangkuban Parahu adalah salah satu gunu...,Cagar Alam,Bandung,30000,4.5,"{'lat': -6.759637700000001, 'lng': 107.6097807}",-6.759638,107.609781
211,212,Jalan Braga,Jalan Braga adalah nama sebuah jalan utama di ...,Budaya,Bandung,0,4.7,"{'lat': -6.9150534, 'lng': 107.6089842}",-6.915053,107.608984

In [ ]:
# Merubah data rating agar hanya berisi rating pada tempat wisata dari Kota Bandung

rating = pd.merge(rating, place[['Place_Id','Place_Name','Category']], how='right', on='Place_Id')
rating.head()

   User_Id  Place_Id  Place_Ratings              Place_Name    Category
0        9       211              3  GunungTangkuban perahu  Cagar Alam
1       26       211              2  GunungTangkuban perahu  Cagar Alam
2       40       211              3  GunungTangkuban perahu  Cagar Alam
3       40       211              2  GunungTangkuban perahu  Cagar Alam
4       70       211              5  GunungTangkuban perahu  Cagar Alam

In [ ]:
# Merubah data user agar hanya berisi user yang pernah megunjungi wisata di Kota Bandung

user = pd.merge(user, rating[['User_Id']], how='right', on='User_Id').drop_duplicates().sort_values('User_Id')
user.head()

In [ ]:
# Melakukan merge antara df user dan rating untuk mendapatkan kolom Age
new = pd.merge(user[['User_Id','Age','Location']], rating, how='right', on='User_Id').drop_duplicates().sort_values('User_Id')
new.head(20)

,User_Id,Age,Location,Place_Id,Place_Ratings,Place_Name,Category
2675,1,20,"Semarang, Jawa Tengah",328,2,Gua Pawon,Cagar Alam
2185,1,20,"Semarang, Jawa Tengah",307,4,Perkebunan Teh Malabar,Cagar Alam
1831,1,20,"Semarang, Jawa Tengah",292,3,Curug Anom,Cagar Alam
2082,1,20,"Semarang, Jawa Tengah",302,2,Masjid Pusdai,Tempat Ibadah
2297,1,20,"Semarang, Jawa Tengah",312,2,Taman Hutan Raya Ir. H. Juanda,Cagar Alam
1241,1,20,"Semarang, Jawa Tengah",265,5,Museum Mandala Wangsit Siliwangi,Budaya
1078,1,20,"Semarang, Jawa Tengah",258,5,Museum Gedung Sate,Budaya
260,1,20,"Semarang, Jawa Tengah",222,3,Museum Konferensi Asia Afrika,Budaya
795,1,20,"Semarang, Jawa Tengah",246,4,Curug Tilu Leuwi Opat,Cagar Alam
2505,2,21,"Bekasi, Jawa Barat",321,3,Glamping Lakeside Rancabali,Taman Hiburan
1612,2,21,"Bekasi, Jawa Barat",281,2,Tektona Waterpark,Taman Hiburan
1178,2,21,"Bekasi, Jawa Barat",262,3,Wot Batu,Cagar Alam
2526,2,21,"Bekasi, Jawa Barat",322,4,Bukit Jamur,Cagar Alam
279,3,23,"Cirebon, Jawa Barat",223,5,Masjid Raya Bandung,Tempat Ibadah
1654,3,23,"Cirebon, Jawa Barat",283,3,Jembatan Pasupati,Taman Hiburan
2255,3,23,"Cirebon, Jawa Barat",310,3,Taman Bunga Cihideung,Cagar Alam
875,3,23,"Cirebon, Jawa Barat",249,3,Upside Down World Bandung,Taman Hiburan
2456,3,23,"Cirebon, Jawa Barat",319,5,Kawah Rengganis Cibuni,Cagar Alam
895,3,23,"Cirebon, Jawa Barat",250,2,Pesona Nirwana Waterpark & Cottages,Taman Hiburan
601,3,23,"Cirebon, Jawa Barat",237,3,Panghegar Waterboom Bandung,Taman Hiburan

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

new_place = place
CountV = CountVectorizer()

CountV.fit(new_place['Category'])

CountVectorizer()

In [ ]:
CountV.vocabulary_.keys()

dict_keys(['cagar', 'alam', 'budaya', 'taman', 'hiburan', 'tempat', 'ibadah', 'pusat', 'perbelanjaan'])

In [ ]:
CountV_matrix = CountV.transform(new_place['Category'])

In [ ]:
pd.DataFrame(
    CountV_matrix.todense(),
    columns=list(CountV.vocabulary_.keys()),
    index = new_place.Place_Name
)

,cagar,alam,budaya,taman,hiburan,tempat,ibadah,pusat,perbelanjaan
Place_Name,,,,,,,,,
GunungTangkuban perahu,1,0,1,0,0,0,0,0,0
Jalan Braga,0,1,0,0,0,0,0,0,0
Gedung Sate,0,1,0,0,0,0,0,0,0
Trans Studio Bandung,0,0,0,1,0,0,0,1,0
Taman Hutan Raya Ir. H. Djuanda,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
Bandros City Tour,0,1,0,0,0,0,0,0,0
Kyotoku Floating Market,0,1,0,0,0,0,0,0,0
Rainbow Garden,1,0,1,0,0,0,0,0,0
Kota Mini,0,0,0,1,0,0,0,1,0
Chingu Cafe Little Seoul,0,0,0,1,0,0,0,1,0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(CountV_matrix)

In [ ]:
cosine_sim_df = pd.DataFrame(cosine_sim,index=new_place['Place_Name'],columns=new_place['Place_Name'])

def simmilar_place_recommendations(place_name, csim=cosine_sim_df, param=new_place[['Place_Id','Place_Name', 'Category']], k=5):
    index = csim.loc[:, place_name].values.argpartition(range(-1, -k, -1))
    res = csim.columns[index[-1:-(k+2):-1]].tolist()
    if place_name in res:
        res.remove(place_name)
    result = param['Place_Name'].isin(res)
    result = param[result].head(2)
    print(result['Place_Id'].values)
    return result['Place_Id'].values

In [ ]:
simmilar_place_recommendations("Gua Pawon")

[211 246]

array([211, 246])